map_type: costmap #Map type to use, "voxel" or "costmap".
obstacle_range: 2.5  
raytrace_range: 3.0  
robot_radius: 0.49  
inflation_radius: 0.1  
max_obstacle_height: 0.6  
min_obstacle_height: 0.0  
obstacles:  
   observation_sources: scan  
   scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0} 

#More information at http://wiki.ros.org/costmap_2d and http://wiki.ros.org/costmap_2d/flat 
